export async function seed(knex) {
    await knex('artists').del();
    await knex('artists').insert([
        { id: 1, artist: "Shadi Al-Atallah" },
        { id: 2, artist: "Michael Alvarez" },
        { id: 3, artist: "Laís Amaral" },
        { id: 4, artist: "Denilson Baniwas" },
        { id: 5, artist: "Creighton Baxter" },
        { id: 6, artist: "Cecilia De Nisco" },
        { id: 7, artist: "Nash Glynn" },
        { id: 8, artist: "Ruth Ige" },
        { id: 9, artist: "Khalil Robert Irving" },
        { id: 10, artist: "Char Jeré" },
        { id: 11, artist: "Libasse Ka" },
        { id: 12, artist: "Sophia Loeb" },
        { id: 13, artist: "Asemahle Ntlonti" },
        { id: 14, artist: "Preston Pavlis" },
        { id: 15, artist: "Grace Rosario Perkins" },
        { id: 16, artist: "Esteban Abdul Raheem Samayoa" },
        { id: 17, artist: "Xie Lei" },
        { id: 18, artist: "Yooyun Yang" },
        { id: 19, artist: "Jenny Holzer" },
        { id: 20, artist: "Shuang Li" },
        { id: 21, artist: "Xaviera Simmons" },
        { id: 22, artist: "Ruben Ulises Rodriguez Montoya" },
        { id: 23, artist: "Tourmaline" },
        { id: 24, artist: "Pope.L" },
        { id: 25, artist: "Kambui Olujimi" },
        { id: 26, artist: "Jessi Reaves" },
        { id: 27, artist: "Jonah Groeneboer" },
        { id: 28, artist: "Sable Elyse Smith" },
        { id: 29, artist: "Erin Jane Nelson" },
        { id: 30, artist: "Juliana Huxtable" },
        { id: 31, artist: "Anicka Yi" },
        { id: 32, artist: "Hương Ngô" },
        { id: 33, artist: "Sondra Perry" },
        { id: 34, artist: "Raúl De Nieves" },
        { id: 35, artist: "Jibade-Khalil Huffman" },
        { id: 36, artist: "Yuji Agematsu" },
        { id: 37, artist: "Kayode Ojo" },
        { id: 38, artist: "Erica Newton" },
        { id: 39, artist: "Gozié Ojini" },
        { id: 40, artist: "Ben Werther" },
        { id: 41, artist: "Joan Jonas" },
        { id: 42, artist: "Doris Guo" },
        { id: 43, artist: "Matthew Langan-Peck" },
        { id: 44, artist: "Isabelle Frances McGuire" },
        { id: 45, artist: "Jesse Darling" },
        { id: 46, artist: "Tracey Emin" }
    ])
}
